onComment:
  set:
    - help wanted

onApproved:
  remove:
    - Review Needed
    - help wanted
    - Needs Changes
  set:
    - Approved

onChangesRequested:
  remove:
    - Approved
  set:
    - Needs Changes
