name: Auto Create Cert PR from Dev

on: 
  push:
    branches:
    - "pink_dev"
    - "blue_dev"

jobs:
  makeBlueCertPR:
    if: github.ref == 'refs/heads/blue_dev'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        
        with:
          source_branch: ${{ github.ref }}
          destination_branch: "blue_cert"
          pr_title: "Pulling ${{ github.ref }} into blue_cert"

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_body: ":crown: *An automated PR*"
          pr_assignee: "zachhorton"
          pr_reviewer: "zachhorton"
          pr_label: "BLUE,auto-pr"

          
  makePinkCertPR:
    if: github.ref == 'refs/heads/pink_dev'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        
        with:
          source_branch: "pink_dev"
          destination_branch: "pink_cert"
          pr_title: "Pulling ${{ github.ref }} into pink_cert"

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_body: ":crown: *An automated PR*"
          pr_assignee: "zachhorton"
          pr_reviewer: "zachhorton"
          pr_label: "PINK,auto-pr"
