name: Auto Create Cert PR from Dev

on: 
  push:
    branches:
    - "origin/blue_dev"
    - "origin/pink_dev"

jobs:
  bluecertPR:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "origin/blue_dev"
          destination_branch: "origin/blue_cert"
          pr_title: "Pulling ${{ github.ref }} into blue_cert"
          pr_body: ":crown: *An automated PR*"
          pr_assignee: "zachhorton"
          pr_reviewer: "zachhorton"
          pr_label: "auto-pr,Ready to merge"
