name: Auto Create Cert PR from Dev

on: 
  push:
    branches:
    - "master"
    - "pink_dev"
    - "blue_dev"

jobs:
  bluecertPR:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "blue_dev"
          destination_branch: "blue_cert"
          pr_title: "Pulling ${{ github.ref }} into blue_cert"
          pr_body: ":crown: *An automated PR*"
          pr_assignee: "zachhorton"
          pr_reviewer: "zachhorton"
          pr_label: "auto-pr,ready"
  
  pinkcertPR:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "master"
          destination_branch: "pink_cert"
          pr_title: "Pulling ${{ github.ref }} into blue_cert"
          pr_body: ":crown: *An automated PR*"
          pr_assignee: "zachhorton"
          pr_reviewer: "zachhorton"
          pr_label: "auto-pr,ready"
